// Generated by scripts/hub/build.py — do not edit by hand (v2.80, the prison square).
//
// Units: tiles are 16 px. Map w/h, npc/door/spawn positions are in tiles; objects, lights and
// effects in pixels. objs: [sprite, x, y, base, top, fps, phase] — x/y is the sprite's top-left,
// base the pixel row where it stands (depth sorting with actors), top = always drawn over actors.
// solid: bit-packed half-tile grid (w*2 × h*2, row-major, MSB first), 1 = blocked.
// HUB_SPRITES: name → [x, y, w, h, frames] in /hub/atlas.png; frames lie side by side.

export const HUB_REV = '14d6b229b7';

export const HUB_ATLAS = { w: 1024, h: 72 } as const;

export const HUB_SPRITES: Record<string, readonly [number, number, number, number, number]> = {
 "forge.anvil": [480, 0, 24, 22, 1],
 "forge.bellows": [652, 0, 20, 15, 1],
 "forge.bench": [309, 0, 44, 26, 1],
 "forge.coal": [443, 0, 36, 24, 1],
 "forge.grindstone": [354, 0, 22, 24, 4],
 "forge.hearth": [0, 0, 48, 72, 4],
 "forge.ingots": [505, 0, 28, 18, 1],
 "forge.quench": [564, 0, 26, 16, 1],
 "forge.rack": [274, 0, 22, 34, 1],
 "kit.barrel": [534, 0, 14, 18, 1],
 "kit.barrel.water": [549, 0, 14, 18, 1],
 "kit.barrow": [591, 0, 26, 16, 1],
 "kit.bucket": [688, 0, 10, 10, 1],
 "kit.crate": [618, 0, 16, 16, 1],
 "kit.crate.dark": [635, 0, 16, 16, 1],
 "kit.lamp": [297, 0, 11, 30, 1],
 "kit.sack": [673, 0, 14, 14, 1],
 "kit.stool": [699, 0, 10, 10, 1],
 "stub.forge": [193, 0, 80, 64, 1]
};

export const HUB_RESIDENTS = ["smith"] as const;

export type HubObjRow = [sprite: string, x: number, y: number, base: number, top: 0 | 1, fps: number, phase: number];
export type HubLightRow = [x: number, y: number, r: number, color: string, kind: string, night: 0 | 1];
export type HubFxRow = [kind: string, x: number, y: number, rate: number];
export interface HubNpcData { id: string; sheet: string; x: number; y: number; face: number; anim: string; name: string }
export interface HubDoorData { x: number; y: number; w: number; h: number; to: string; at: string; kind: string; label: string; lock: string }
export interface HubMapData {
  id: string; name: string; kind: 'indoor' | 'outdoor'; w: number; h: number;
  ambient: number; music: string; bg: string; solid: string;
  objs: HubObjRow[]; npcs: HubNpcData[]; doors: HubDoorData[]; lights: HubLightRow[]; fx: HubFxRow[];
  spawns: Record<string, [number, number, number]>; marks: Record<string, [number, number]>;
  searchlights: [number, number, number][];
}

export const HUB_MAPS: Record<string, HubMapData> = {
 "square": {
  "id": "square",
  "name": "Площадь",
  "kind": "outdoor",
  "w": 24,
  "h": 20,
  "ambient": 1.0,
  "music": "yard",
  "bg": "#6e5a44",
  "solid": "////////////////wAAAAAADwAAAAAADwAAAAAADwAAAAAADwAAAAAADwAAAAAADwP/AAAADwP/AAAADwP/AAAADwP/AAAADwP/AAAADwP/AAAADwAAAAAADwAAAAAADwAAAAAADwAAADAADwAAAAAADwAAAAAADwAAAAAADwAAAAAADwAAAAAADwAAAAAADwAAAAAADwAAAAAADwAAAAAADwAAAAAADwAAAAAADwAAAAAADwAAAAAADwAAAAAADwAAAAAADwAAAAAADwAAAAAADwAAAAAADwAAAAAADwAAAAAAD///8P//////8P///",
  "objs": [
   ["stub.forge", 64, 48, 112, 0, 0, 0],
   ["kit.crate", 224, 128, 144, 0, 0, 0]
  ],
  "npcs": [],
  "doors": [
   {
    "x": 6,
    "y": 6.4,
    "w": 1,
    "h": 0.6,
    "to": "forge",
    "at": "in",
    "kind": "enter",
    "label": "Кузница",
    "lock": ""
   },
   {
    "x": 11,
    "y": 19.4,
    "w": 2,
    "h": 0.6,
    "to": "@back",
    "at": "",
    "kind": "exit",
    "label": "Выход",
    "lock": ""
   }
  ],
  "lights": [],
  "fx": [],
  "spawns": {
   "forge": [6.5, 7.8, 0],
   "kpp": [12, 17, 1]
  },
  "marks": {},
  "searchlights": []
 },
 "forge": {
  "id": "forge",
  "name": "Кузница",
  "kind": "indoor",
  "w": 11,
  "h": 13,
  "ambient": 0.6,
  "music": "yard",
  "bg": "#120c10",
  "solid": "///////////////////////wAP/AA//nD/+d/AAH8AAfwAAP/MA/94DwHgPAAA/wAD/8/P/z88ADf8AN/8AH/wAf/w///D/w",
  "objs": [
   ["forge.hearth", 16, 8, 80, 0, 7, 0],
   ["forge.bellows", 64, 65, 80, 0, 0, 0],
   ["forge.anvil", 76, 112, 134, 0, 0, 0],
   ["forge.quench", 20, 106, 122, 0, 0, 0],
   ["kit.bucket", 51, 110, 120, 0, 0, 0],
   ["forge.coal", 15, 140, 164, 0, 0, 0],
   ["kit.barrow", 52, 146, 162, 0, 0, 0],
   ["forge.grindstone", 110, 70, 94, 0, 4, 0],
   ["forge.rack", 138, 78, 112, 0, 0, 0],
   ["forge.bench", 98, 144, 170, 0, 0, 0],
   ["kit.stool", 115, 163, 173, 0, 0, 0],
   ["kit.crate", 143, 177, 193, 0, 0, 0],
   ["forge.ingots", 132, 170, 188, 0, 0, 0],
   ["kit.crate.dark", 143, 163, 179, 0, 0, 0],
   ["kit.barrel", 17, 168, 186, 0, 0, 0],
   ["kit.barrel.water", 33, 175, 193, 0, 0, 0],
   ["kit.sack", 17, 180, 194, 0, 0, 0],
   ["kit.lamp", 115, 90, 120, 1, 0, 0]
  ],
  "npcs": [
   {
    "id": "smith",
    "sheet": "smith",
    "x": 5.5,
    "y": 6.85,
    "face": 0,
    "anim": "work",
    "name": "Кузнец"
   }
  ],
  "doors": [
   {
    "x": 4,
    "y": 12.35,
    "w": 2,
    "h": 0.65,
    "to": "square",
    "at": "forge",
    "kind": "exit",
    "label": "Выйти",
    "lock": ""
   }
  ],
  "lights": [
   [40, 70, 96, "#ff8a3a", "forge", 0],
   [86, 112, 34, "#ffb347", "glow", 0],
   [120, 130, 58, "#ffd98a", "lamp", 0],
   [88, 54, 40, "#9fc4d0", "window", 0]
  ],
  "fx": [
   ["embers", 40, 62, 1.4],
   ["smoke", 40, 28, 0.5],
   ["sparks", 86, 110, 1.0],
   ["steam", 38, 108, 0.3]
  ],
  "spawns": {
   "in": [5.0, 11.4, 1]
  },
  "marks": {
   "smith": [5.5, 6.85]
  },
  "searchlights": []
 }
};
