[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production]
PORT = "$PORT"
DATABASE_URL = "$DATABASE_URL"
JWT_SECRET = "$JWT_SECRET"
CORS_ORIGIN = "$CORS_ORIGIN"
NODE_ENV = "production"

[environments.development]
PORT = "3000"
NODE_ENV = "development"