// Этаж 1 — «Крысиные норы». КАРКАС v2.81: здесь перенесено содержимое
// подземелья до этажей как есть (Вход в шахты и Рельсовые туннели, крысы,
// Крысиный король, пиритовые шахты) — чтобы игра и тесты работали, пока
// этаж не переработан. Агент первого этажа переделывает его целиком.

import type { MobDef } from '../dungeon';
import { MAP_HAUL, MAP_MOUTH } from '../dungeon-maps';
import type { FloorDef } from './types';

/** Король платит постоянно: 8 000 монет, корона, шкурки. */
const KING_COINS = 8_000;

const MOBS: MobDef[] = [
  {
    id: 'rat',
    name: 'Серая крыса',
    many: 'серых крыс',
    hp: 14,
    dmg: 9,
    speed: 3.7,
    radius: 0.26,
    windup: 0.26,
    reach: 0.34,
    rest: 0.55,
    xp: 3,
    meat: ['meat', 0.7, 1],
    mats: [['skin', 0.22]],
    beast: true,
    brain: 'melee',
    art: { kind: 'rat' },
    mass: 1,
    flinch: 0.35,
    zigzag: true,
  },
  {
    id: 'fatrat',
    name: 'Жирная крыса',
    many: 'жирных крыс',
    hp: 46,
    dmg: 18,
    speed: 2.1,
    radius: 0.36,
    windup: 0.5,
    reach: 0.42,
    rest: 1,
    xp: 9,
    meat: ['fatmeat', 1, 2],
    mats: [['skin', 0.6]],
    beast: true,
    brain: 'melee',
    art: { kind: 'rat' },
    mass: 2.6,
    flinch: 0,
    stunT: 0.14,
    hit: { push: 5 },
  },
  {
    id: 'bomber',
    name: 'Крыса-подрывник',
    many: 'подрывников',
    hp: 16,
    dmg: 30,
    speed: 3.2,
    radius: 0.26,
    windup: 1.5,
    reach: 1.4,
    rest: 2,
    xp: 7,
    meat: ['meat', 0.6, 1],
    mats: [
      ['tail', 0.5],
      ['skin', 0.2],
    ],
    beast: true,
    brain: 'bomber',
    art: { kind: 'rat' },
    mass: 1,
    flinch: 1,
  },
  {
    id: 'goldrat',
    name: 'Золотая крыса',
    many: 'золотых крыс',
    hp: 40,
    dmg: 0,
    speed: 5.2,
    radius: 0.27,
    windup: 0,
    reach: 0,
    rest: 0,
    xp: 25,
    meat: null,
    mats: [['skin', 1]],
    beast: true,
    brain: 'flee',
    art: { kind: 'rat' },
    mass: 1,
    flinch: 1,
    noAlbino: true,
    coins: 1_500,
    eye: '#fff0a0',
    gore: ['#d8a83a', '#fff0a8', '#8a6418'],
    resume: 'flee',
  },
  {
    id: 'king',
    name: 'Крысиный король',
    many: 'крысиных королей',
    hp: 1750,
    dmg: 16,
    speed: 2.4,
    radius: 0.95,
    windup: 0.8,
    reach: 0.6,
    rest: 1.2,
    xp: 450,
    meat: ['fatmeat', 1, 12],
    mats: [['crown', 1]],
    beast: true,
    brain: 'king',
    art: { kind: 'rat' },
    mass: 9,
    boss: true,
    noAlbino: true,
    eye: '#ffcc30',
  },
  {
    id: 'kinglet',
    name: 'Малый король',
    many: 'малых королей',
    hp: 260,
    dmg: 16,
    speed: 3.2,
    radius: 0.55,
    windup: 0.6,
    reach: 0.4,
    rest: 1,
    xp: 60,
    meat: ['fatmeat', 1, 3],
    mats: [['skin', 1]],
    beast: false,
    brain: 'king',
    art: { kind: 'rat' },
    mass: 4,
    boss: true,
    noAlbino: true,
    eye: '#ffcc30',
  },
];

export const F1: FloorDef = {
  id: 1,
  name: 'Крысиные норы',
  lead: 'Старые выработки под лагерем. Крысы, гнёзда и логово их короля.',
  mapVer: 2,
  // Снизу вверх: вход с лифтом, выше — туннели и логово.
  areas: [
    {
      id: 'mouth',
      name: 'Вход в шахты',
      lead: 'Пещеры у лифта. Фонари горят, крыс немного.',
      tier: 1,
      level: 0,
      ambient: 0.62,
      rows: MAP_MOUTH,
      skin: { floor: 'slab', wall: 'brick' },
      mine: 'pyrite1',
      spawn: {
        mobs: [
          ['rat', 80],
          ['fatrat', 14],
          ['bomber', 6],
        ],
        density: 1,
        pack: [2, 2],
        filler: 'rat',
        group: (i, _n, rnd) => (i === 0 && rnd() < 0.3 ? 'bomber' : 'rat'),
        horde: (rnd) => (rnd() < 0.85 ? 'rat' : 'fatrat'),
        treasure: 'goldrat',
        nest: (cart, rnd) => (cart && rnd() < 0.3 ? 'fatrat' : 'rat'),
      },
    },
    {
      id: 'haul',
      name: 'Рельсовые туннели',
      lead: 'Вагонетки, гнёзда и логово Крысиного короля.',
      tier: 2,
      level: 1,
      ambient: 0.4,
      rows: MAP_HAUL,
      skin: { floor: 'ground', wall: 'rock' },
      mine: 'pyrite2',
      spawn: {
        mobs: [
          ['rat', 55],
          ['fatrat', 26],
          ['bomber', 19],
        ],
        density: 1.25,
        pack: [2, 3],
        filler: 'rat',
        group: (i) => (i % 2 === 0 ? 'fatrat' : 'rat'),
        horde: (rnd) => (rnd() < 0.85 ? 'rat' : 'fatrat'),
        treasure: 'goldrat',
        nest: (cart, rnd) => (cart && rnd() < 0.3 ? 'fatrat' : 'rat'),
        carts: true,
      },
    },
  ],
  boss: {
    id: 'king',
    name: 'Крысиный король',
    lead: 'Логово в Рельсовых туннелях',
    area: 'haul',
    restMs: 20 * 60_000,
    mob: 'king',
    script: 'king',
    parts: ['king', 'kinglet'],
    loot: (rnd) => ({
      tokens: 20 + Math.floor(rnd() * 20),
      keys: rnd() < 0.4 ? 1 : 0,
      coins: KING_COINS,
      mats: { crown: 1, skin: 6 + Math.floor(rnd() * 6) },
    }),
  },
  mines: [
    {
      id: 'pyrite1',
      name: 'Шахта у входа',
      area: 'mouth',
      windowMs: 60 * 60_000,
      ores: [0, 1],
      share: [0.14, 0.2, 0.26, 0.32, 0.4],
      pyrite: 0.5,
      blocks: 1.2,
    },
    {
      id: 'pyrite2',
      name: 'Глубокая шахта',
      area: 'haul',
      windowMs: 3 * 60 * 60_000,
      ores: [0, 1],
      share: [0.22, 0.3, 0.38, 0.46, 0.55],
      pyrite: 0.5,
      blocks: 2,
    },
  ],
  mobs: MOBS,
  meats: [
    { id: 'meat', name: 'Крысятина', price: 25, heal: 0.15 },
    { id: 'fatmeat', name: 'Жирная крысятина', price: 45, heal: 0.25 },
  ],
  mats: [
    { id: 'skin', name: 'Крысиная шкурка', price: 20, lead: 'На заточку снаряжения.' },
    { id: 'tail', name: 'Хвост подрывника', price: 35, lead: 'Фитиль в нём не догорел.' },
    {
      id: 'pyrite',
      name: 'Пирит',
      price: 70,
      lead: '«Кошачье золото» из подземных шахт — для каски и улучшений.',
    },
    {
      id: 'crown',
      name: 'Корона Крысиного короля',
      price: 6_000,
      lead: 'Трофей. Нужен, чтобы улучшить снаряжение до Кованого.',
      stack: 1,
    },
  ],
  music: { explore: 'depths', boss: 'boss' },
  cover: '/ui/areas/mouth.png',
};
