// Карты этажа 13 — собраны скриптом scripts/dungeon/f13.py (кисти brush.py).
// Руками не править: запустите скрипт, он перепишет файл.
// Район 1 — «Внешний район» (вход), 2 — «Ворота и стена», 3 — «Площадь колокола» (арена Колосса).
// F13_HOOKS — пары «столб → кольцо» в местных координатах района.

export const MAP_F13_OUTER: string[] = [
  '############################ssssssss############################',
  '############################ssssssss####################A#######',
  '############################ssssssss############################',
  '############################ssssssss############################',
  '############################ssssssss##############A#############',
  '########################[][Ussssssss#]#]########################',
  '#######QJ##########Q####ssssssssssssssss####Q###################',
  '########################ssxsssskssssssss########################',
  '######################]]ssssssqqqqs2ssss]]######################',
  '#####################hhhssssssqqqqssjssshhh#####################',
  '#################Q###hhhsjsss;qqqq;ssssshhh#####################',
  '#####################hhhssssssqqqqsssssshhh#############Q#######',
  '#########Q#############ossssssqqqqsssnss########################',
  '########################ssjsssqqqqssssss########################',
  '########################sssessqqqqssssss###################J####',
  '########################ssssssqqqqssssss########################',
  '######################J#ssssssqqqqsssssso##########J############',
  '########################sssss;qqqq;sssss#################Q######',
  '########################ssssssqqqqssssss#U#################J####',
  '#####################hhhssssssqqqqsssssshhh############Q########',
  '#####################hhhssss1sqqqqsssssshhh#####################',
  '#####################hhhksssssqqqqsssssshhh#####################',
  '########J###############stsssxqqqqsssssj######J##Q##############',
  '########################ssssskqqqqjsssss###############A########',
  '########################sssss;qqqq;sssss#Q######################',
  '##Q#####################ssssssqqqqssssss####################J###',
  '########################ssssssqqqqssssss############Q###########',
  '#################]]#]#[#ssssssqqqqsxss/s########################',
  '##########Q#ssssssssssskssssssqqqqssssss[[#########J############',
  '#A###J######ssskssssssssssssssqqqqssskskhhh#####################',
  '############ssssssssssksssssssqqqqsssssshhh#####################',
  '############sssssssssssssssss;qqqq;ssssshhh#####################',
  '############ssss########ssssssqqqqssxsss#########J##########Q###',
  '############scss#######osssssjqqqqssssss########################',
  '############ssss########ssssssqqqqssesss##Q#####Q###############',
  '############ssss########ssssssqqqqssssss]]######################',
  '########J##ossss########ss*sksqRqqsssssssssssssssss#############',
  '############ssss########ssssssqqqqsssssssssssssssss#############',
  '############ssss#####]][sssss;qqqq;ssssssssssssssss#############',
  '############ssss#####hhhssskssqqqqsssssssssssssssss#############',
  '##JQ########ss<s#####hhhssssssqqqqsssssshhh##ssssso#############',
  '############ssss#####hhhssesssqqqqsssssshhh##sssss##############',
  '############ssssQ#######ssssssqqqqssssss#####sssbs##############',
  '#########J##ssss########sssxssqqqqsssssso####sssss##############',
  '############ssss########ssssssqqqqs7ssss#####sssss############Q#',
  '#####Q#Q####ssss########ssssssssssssssss#####s<sss##############',
  '##########Q#ssss########ssssksssssssssss##J##sssss###U##]#######',
  '##########Q#sssz#Q##Q#A#########ss#########sssssss:::hhhhhhhh###',
  '############sssz############A##Qss#########sssssss:::hhhhhhhh###',
  '############ssks#############J##ss#####A###sssssss:::hhhhhhhh###',
  '#######Q####s}ss########Q#######ss#J######osssssss:::hhhhhh7h###',
  '######A###J#szss##Q#QQ####sssDssss#########sssssss:::hhhhhhhh###',
  '############ssss#######Q##ss###############ss<ssss:::hhhhhhhh###',
  '############zzszo#########ssYYYYYYYYY###J##sssssss:::hhhhhhhh###',
  '############zszs##########ssYYYYYYYYY######sssssss:::hhhhhhhh###',
  '####zszssszzzzzsssssssQ###ssYkkkkkkYY###Q##sssssss:::hhhhhhhh###',
  '####szsssssssszsssztssQ#[]ss/kkkkkk/Y]#####ssssssshhhhhhhhhhh###',
  '####zslzsssszszsszssss#9qqqqqqqqqqqqqqqq9##ssssssshhhhhhhhhhh###',
  '####zsszssszszsksssszs#qqkqqqqkqqqqqqqqqq##kssRkss:::hhhhhhhh###',
  '##A#ssss####ssks#######qqssssssssssssssqq##sssssss:::hhППMПППJ##',
  '#Q##ssss####ssss######Qqqspsssssssssspsqqo#sssssss:::hh,,,,ПП###',
  '####s}ss####zszn#######qqssssssssssssssqq##sssssss:::hhПП,,ПП###',
  '####ssss####ssRz######oqqsssssksstsssssqq##sssssss:::hhПП6,ПП###',
  '####ssss####kzzs####Q##qqssssssssssssssqq##ssss^ss:::0hПП,,ПП###',
  '###Qssss####zssz##Q####qqssssss1xsssssspq##sssssss:::hhПП,,ПП###',
  '####Qs##A###szss#######qqssssssssssssssqq##sssss0s:::h^ПП,,ПП###',
  '#####%######zssssssssssqqssssqqqqqqssssqq##sssssss:::hh,,,,ПП###',
  '###zzzzz####szszsssssssqqssssqqqqqqssssqq##sssssss:::hh,,,,ПП###',
  '##Qzz$zz#JQ#sssssssssssqqssssqqqqqqssssqq##sssssss:::hhПП,,ППQ##',
  '###zzzzz####sssssssssssqqssssqq8qqqssssqq]#sssssss:::hhПП,,ПП###',
  '###zzzzu###ozzss#######qpssssqqqqqqsxssqqssssssssd:::hhПП,6ПП###',
  '####Q#######skss######Qqqssssqqqqqqssssqqsssbsssss:::hhПП,,ПП###',
  '#########Q##zszz##Q####qqssssqqqqqqssssqqsssssssss:::hhПП,,ПП###',
  '#Q##########szsk#######qqsssskqqqqqssssqqsssssssss:::hh,,,,ПП#J#',
  '######Q#QQ##ss/s#######qqssssssssssssssqqQ#sksssss:::hhПППППП###',
  '########A#Q#szss#######qqsscsssssssssssqq##ssdssss:::hhhhhhhh###',
  '###########Qsszs#######qqssssssRssssbssqq##sssssss:::hhhhhhhh###',
  '#####A####Q#zzss#######qkssssssssssssssqq##ssssssshhhhhhhhhhh###',
  '###Q#####Q##ssss##Q####qqssssssssssssssqq#ossskssshhhhhhhhhhh###',
  '##########A#zzss#######qqspkssssssssspsqq##sssscss:::hhlhhhhh###',
  '#ППППП######zzzs#######qqssssssssssssssqq##sssssss:::hhhhhhhh###',
  '#ППППП######zzss##Q####qxqqxqqqqqqqqqqqqq##ssdssss:::hhhhhhhh###',
  '#ППППП######ssss##QQ###9qqqqqqqqqqqqqqqq9##sssssss:::hhhhhhhh###',
  '#QПППП##U#####Q##U###o[[##]#[ssssssU]][##U]########]]]]]U#######',
  '#П,,,,,sssssssssssssssssssssssssssskssssssssssssssssssssss######',
  '#П,,,,,stsssssssssssssss;sssssssssssssss;sssssssssss/sssss######',
  '#П,,,,,sssssssssssRssksssssssssssssssskssssssssssssssssssso#####',
  '#П,,,Пssssssssssssssssssssssssssss0ssssssssss0ssssssssssss######',
  '#П,,,П_______s______sssss____ss^ssss_____ssksss^sss_______######',
  '#П,,,П____________________________________________________######',
  '#П,d,П____________________________________________________######',
  '#П,,,П____________________________________0kk$kk__________######',
  '#П,,,П____________________________________kk^kkk__________######',
  '#П,,,П____________________________________k^kk0k__________######',
  '#П,,,П____________________________________________________######',
  '#П,,,П____________________________________________________######',
  '#П,a,П_____####______________sssss^s_#####ssss^ss_________######',
  '#П,,,Пsssssssssssssksssssssssss0ssssssksssss0sssssssssssss######',
  '#П,,,Пssssssssskssss<sssssksssssssssssssssssssssssssssscss######',
  '#П,,,Пssssssssssssssssssssssssssssssssssssssssssssssssssks######',
  '#П,,,П###o#A############]]]]#ssssss]]U]]U#########o#############',
  '#П,,,П##################.....ssssss......#############A#########',
  '#П,,,П##################.;...ssssss....;.#######################',
  '#П,,,ППППППППППППППППППП.....ssssss......#######################',
  '#П,,,ППППППППППППППППППП...i.ssssss......#######################',
  '#П,,,ППППППППППППППППППП..............t..#################Q#####',
  '#П,,,,,,,,,,,,,,,,,,,,,,.................#######################',
  '#П,,,,,,,,,,d,,,,,,,,,,,.................#######################',
  '#П,,,,,,,,,,,,,,,,,,,,,,.................#######################',
  '#ППППППППППППППППППППППП.................#######################',
  '#ППППППППППППППППППППППП..u............*.#######################',
  '#ППППППППППППППППППППППП.................#######################',
  '########################........E........#######################',
  '###########J##Q#########.................########Q##########Q###',
  '########################.................####################J##',
  '########################.................#######################',
  '############J###########..c...........b..#######################',
  '########################<...........l....#########Q#############',
  '########################.................##################Q####',
  '################################################################',
  '#################################J#####J########################',
  '################################################################',
  '################################################################',
  '################################################################',
];

export const MAP_F13_WALL: string[] = [
  '##########################ssssssssssss##########################',
  '##########################ssssssssssss##########################',
  '######################J##Assssssssssss##########################',
  '##########################ssssssssssss##########################',
  '##########################ssssqqqqssss##########################',
  '##########################ssssqqqqssss##########################',
  '#Q#########J##############ss;sqqqqs;ss##########################',
  '##########################ssssqqqqssss##########################',
  '###################Q######ssssqqqqssss##########################',
  '##########################ssssqqqqssss#################J########',
  '##########################stssqqqqssss######################Q###',
  '################J#########ssssqqqqssss############A########Q##Q#',
  '##########################ssssqqqqssss##########################',
  '########################A#ss;sqqqqs;ss##########################',
  '##########################ssssqqqqssss##########################',
  '##########################ssssqqqqssss##########################',
  '##########################ssssqqqqss/s###################J##Q###',
  '#######J############Q#####ssssqqqqssss##########################',
  '##########################ssssqqqqssss##########################',
  '##########]U###########U#[ssssqqqqssss#]U]#####[#U##############',
  '##########ssssssssssssssssssssssssssssssssssssssssssss##########',
  '##########ssssssssssssssssssssssssssssssssssssssssssss##########',
  '##########sssssssssssssscsssssssssssssscssssssssssxsss##########',
  '#######J##ssssssssssssssssssssssssssssssssssssssssssss##########',
  '##########ss##Q#######ssssssssssssssssssss########J#ss##########',
  '#########oss##########ssssssssssssssssssss##########sso#########',
  '##########ss##########ssssssssssssssssssssJ#########ss##########',
  '##########sso########osssssssssssssssssssso########oss##########',
  '##########ss##########ssksssssssssssssssss##########xs##Q#######',
  '###J######ss##########ssssssssssssssssssss##########ss##########',
  '##########ss]]#######]sssssssssss5ssssssss#]########ss##########',
  '##########ssssssssssssssssssssssssssssssssssssssssssss##########',
  '##########ssssssssssssssssssssssssssssssssssssssssssss##########',
  '##########ssssssssksssss;sssssssssssssss;sssssssssssss##########',
  '##########7sssssssssRsssssskssssssssssssssssssssssssss##########',
  '###J######ssssssssssssssssssssssssssssssssssssssss1sss##########',
  '####Q#####ssssssssssssssssssssssssssssssssssssssssssss##########',
  '#######]]#ssssssssssssssssssssssssssssssssssssssssssss#][#######',
  '###sssssssssssssssssssssssss1ssksssssssskssssssssssssssssssss###',
  '##Jssssssssssssssssssssssssssssssssssssssssssssssssssssssskss###',
  '###ssbbsssssssssssssss{skssssssssssssssss{ssssssssssssssssbss###',
  '###ssbsssssssssssssssssssssssssssssssssssssssssssssssssssbsss###',
  '###sssssssss#######sssssssxssssssssssssssssssssss#######sssss###',
  '###sssssssss#######sssssssssshh+hhhssssssssssssss#######sssss###',
  '###sssssssss######osssssssssshhhhhhsssssssssssssso######sssss###',
  '###sssssRsss#######sssssssXsshhhhhhssXsssssssssss#######sssss###',
  '###sssssskss#][####sssssssssshhhhhhssssssssssssss##]####sssss###',
  '###sssssssssksssssssssssssssshhhhhhssssssssssssssssssssssssss###',
  '###sssssssssssssssssssssssssssssssssssssssssssssssssssssscsss###',
  '##WWWWWscsssssssssssssssssssssssssssssssssssRssssssssssssssss###',
  '##WWWWWsssssssssssss;ssssssssssssss;sskssss(sssssssskssssssss###',
  '##WWWWWsssssssssssssssssssssxssssssssssssssssss?sssssssssssss###',
  '##,,D,,,sssssssssssssssssssssssssssssssssssssssssssssssssssss###',
  '##,WWWWssssssssssssssssssssssssssssssssssssssskssssssssssssss###',
  '#W,WWWWWwwWWWWWWWWWWWWWWWWWWWWWW%WWWWWWWWWrrrrWWWWWWWWWwwWWWWWW#',
  '#W,WWWWWwwWWWWWWWWWWWWWWWWWWWhh$hhhWWWWWWWrrrrWWWWWWWWWwwWWWWWW#',
  '#W,WWWWWwwWWWWWWWWWWWWWWWWWWWhhhh{hWWWWWWWrrrrWWWWWWWWWwwWWWWWW#',
  '#W,WWWWWwwWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWrrrrWWWWWWWWWwwWWWWWW#',
  '#W,WWbwwwwwwwww^0wwwwwwwwwwwwwcwwww^0wwww-rrrr-wwwwwww^0wwwwwWW#',
  '#W,WWwwwwwwwwww{wwwwwwwwwwwwwwwww{wwwwwww-rrrr-wwwwwwww{wwwwwWW#',
  '#W,WWwwwwwZwwwwwwwwwZwwwwwZwwwwwwwwwwZwww-rrrr-wwwwwZwwwwwZwwWW#',
  '#N,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNrrrrNNNNNNNNNNNNNNNNN#',
  '#W,WWWWWWWWWWWWWWWWWWWWWWWWWWIIIIIIWWWWWWWrrrrWWWWWWWWWWWWWWWWW#',
  '#W,WWWWWWWWWWWWWWWWWWWWWWWWWWIIIIIIWWWWWWWrrrrWWWWWWWWWWWWWWWWW#',
  '#W,WWWWWWWWWWWWWWWWWWWWWWWWWWIIIIIIWWWWWWWrrrrWWWWWWWWWWWWWWWWW#',
  '#W,WWWWWWWWWWWWWWWWWWWWWWWWWWIIIIIIWWWWWWWrrrrWWWWWWWWWWWWWWWWW#',
  '#W,WWWVWWUWWVWWWWWVWWUWWVWWUWIIIIIIWUWVWWWrrrrWWWWVWWUWWVWWWWWW#',
  '##,....g.......0^k....x...k........0^....g.........x..0^...kg###',
  '###............................gk.............kg...gg........###',
  '###........k..gg..........g.......k....g..k.........g...g....###',
  '###g....}......x......v.g...................k.v.xk..}...kk...###',
  '#Q#.g.......k.gg....k...g....k..g..........g.g.gx............###',
  '###..g###...g........g..g...........e....k..k.....k.....g...k###',
  '###...##]..g...........x...k..........k.....4.k.........g....###',
  '###...........g.....k.g.ng.k........x.k...g...........g......###',
  '###......eeeg...k....k.k................................g....#Q#',
  '###......eee.....x........................g......####....n...###',
  '###.gg.x.eee....g.....k..x.....g.................####........###',
  '###...............k............gg.......k....g...####........###',
  '###...k..x.......*........g...............geee...####g.......###',
  '###../..x...........g....g....v..v.k.......eee.......g.......###',
  '###........k....g.......g.k.....g........x.eee.......g.......###',
  '###..g...x.x..n..........g.......g................k..k.......###',
  '###...............g..................k.k.k..k.............gk.###',
  '###.............####........gg...g..../k..k......g......../.k###',
  '###..x...k......####...k.../......k........g.....x....g.....k###',
  '###.........3...]###.............g.kk..............g...g.....###',
  '###............k...eee...g.............k.....g........g....g.###',
  '###k.........g..k.geee......ssssssss...k2....xgn....3.g......###',
  '###.k..............eee.k....ssssssssk.........g.............x###',
  '###...e.................1g..ssssssss...g...x...g.....eee.....###',
  '###g.g................k.....ssssssss.....k.........kxeee....g###',
  '###........gv........x.g....ssssssss....}....x...x.k.eee.....Q##',
  '###.g.............}..g....g.ssssssss..........kk.............###',
  '###...g........g...k........ssssssss.kg...&....g..........gg.###',
  '###g.g......................ssssssss.gk..x.....g.........k..g###',
  '###################Q########ssssssss############################',
  '############################ssssssss############################',
  '############################ssssssss###########J################',
  '################J###########ssssssss############################',
  '############################ssssssss############################',
  '############################ssssssss######A########A#######QQ###',
  '##################Q##Q######ssssssss##Q#####Q###################',
  '############################ssssssss############################',
];

export const MAP_F13_BELL: string[] = [
  '#ПППППППППППППП#################################################',
  '#ПППППППППППППП#################################################',
  '#ПППППППППППППП#################################################',
  '#ПППППППППППППП#####################################Q###########',
  '#ПП,,,,,,,,,,,П#################################################',
  '#ПП,,,,,,,,>,,П###############################################Q#',
  '#ПП,,,,,,,,,,,П#################################################',
  '#ПП,,,,ПППППППП#################################################',
  '#ПП,,,,ПППППППП###########OOOOOOOOOOOO##########################',
  '#ПП,,,,ПППППППП###########OOOOOOOOOOOO######################Q###',
  '#ПП,,,,ПППППППП###########OOOOOOOOOOOO##########################',
  '#ПП,,,,ПППППППП###########OOOOOOOOOOOO##########################',
  '#ПП,,,,ППППППППmmmmmmmmmmmOOOOOOOOOOOOmmmmmmmmmmm###############',
  '#ПП,,,,ППППППППmmmmmmmmmmmOOOOOOOOOOOOmmmmmmmmmmm###############',
  '#ПП,,,,ППППППППmmmmm;mmmmmOOOOOOOOOOOOmmmmm;mmmmm###############',
  '#ПП,,,,ППППППППmmmmmmmmmmmOOOOOOOOOOOOmmmmmmmmmmm###############',
  '#ПП,,,,ППППППППm9mmmmmmmmmmmmmmmmmmmmmmmmmmmmmm9m###############',
  '#ПП,,,,ППППППППmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm###############',
  '#ПП,,,,ППППППППmmmmymmmmmymmmmmymmmmmmymmmmmymmmm###############',
  '#ПП,,,,ППППППППmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm###############',
  '#ППSSSSППППППППmmffmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm###############',
  '#ПП,,,,ППППППППmmmmffmmmmmmmmmmmmmmmmmmmmmmmmmZmm########J######',
  '#ПП,,,,ППППППППmmmmmmffmmmmmmmmmmmmmmmmmmmmmmmmmm###############',
  '#ПП,,,,ППППППППmmmmmmmmffmmmmmmmmmmmmmmmmmmmmmmmm###############',
  '#ПП,,,,ППППППППmmmmymmmmmyfmmmmymmmmmmymmmmmymmmm#############J#',
  '#ПП,,,,ППППППППmmmmmmmmmmmmfmmmmmmmfmmmmmmmmmmmmm###############',
  '#ПП,,,,ППППППППm9mmmmmmmmmmmmmmmmmmmffmmmmmmmmm9m###############',
  '#ПП,,,,ППППППППmmmmmmmmmmmmmmmmmmmmmmmfmmmmmmmmmm###############',
  '#ПП,,,,ППППППППmmmmmmmmmmmmmmmmmmmmmmmmffmmmmmmmm###############',
  '#ПП,,,,ППППППППmmmmmmmmmmmmmmmmmmmmmmmmmmfmmmmmmm###############',
  '#ПП,,,,ППППППППmmmmymmmmmymmmmmKmmmmmmymmmffymmmm#J#############',
  '#ПП,,,,ППППППППmmZmmmmmmmmmmmmmmmmmmmmmmmmmmfmmmm###############',
  '#ПП,,,,ППППППППmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmffmm###############',
  '#ПП,,,,ППППППППmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm###############',
  '#ПП,,,,ППППППППmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm#############J#',
  '#ПП,,,,ППППППППmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm##########Q####',
  '#ПП,,,,ППППППППm9mmmmmmm9mmmmmmmmmmmmmm9mmmmmmm9m###############',
  '#ПП,,,,ППППППППmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm#########A#####',
  '#ПП,,,,ПППППППП###############GGGG##############################',
  '#ПП,,,,ПППППППП###############ssss##############################',
  '#ПП,,,,Пsssssssssssssssssssssssssssssssssssssssssssssssss#######',
  '#ПП,,,,Пsssssssssssssssssssssssssssssssssssssssssssssssss#######',
  '#ПП,,,,ПssssssssssssssssssssTssssssssssssssssssssssssssss#######',
  '#ПП,,,,Пsssssssssssssssssssssssssssssssssssssssssssssssss#[#####',
  '###sssssssssssssssssskskssss######sssssssssssssssssssssssssss###',
  '###sssssssssssssssssssssssss######sssssssssssssssssssssssssss###',
  '###sssssssssssssssssssss|sssQ#####ssssssssssssssssssssssss/ss###',
  '###ss|ssssssssssssssssssssks######sssssssssssssssssssssssssss###',
  '##Qsssssssssssssssssssssssss#####ossss/sssssssssssssssssssssso##',
  '###sssssssssssssssssssssssss######sssssssssssssssssssssssssss###',
  '###sssssssssssssssksRssssssso#####sssssssssssssssssssssssssss###',
  '###sksssssssssssssssssssssss######sssssssssssssssssssss^s0sss###',
  '###sssssssssssssssssssssssss######sssssssssssssssssssssssssss###',
  '########sssss##################QQ#_____.....________________.###',
  '########sssss########Q#########Q##___________________________###',
  '########ssssso####################___________________________###',
  '########sssssJ####################_______________kkk0k_______J##',
  '########sssss#####################_______________0kkkk_______###',
  '########sssss#################Q###_______________kkk^0_______###',
  '###U]]U#sssss####]#]MU#[[]########_______________k^kk^_______###',
  '###....#sssss##Qqgqqqqqqgqqg#Q####______________________kk$k_###',
  '###....#sssss###qqqqqggqqqqq######______________________k^kk_###',
  '###.$..%sssss###qq|qqqqqqqqq######______________________kk0k_###',
  '###....#sssss[##qqqqqgqqq|qq#####J_______kkkkk_______________###',
  '###..|.#ssssssssqqqgqqqqqqqg###A##_______0kk0k_______________###',
  '########ssssssssqqgqgq5qgqqq######_______kkk^k_______________###',
  '########ssssssssqqgqqqqqqqqq###J##_______k^kkk_______________###',
  '########sssss###qqqqqgqqqgqq######___________________________###',
  '########sssss###qqqqqqqqqggq######___________________________###',
  '########sssssQ##gqqqq|qqqqqq######___________________________###',
  '########sssss###q|qqqqqqqq|q######___________________________###',
  '########sssss###qqgqqqgqqgqq######_......____________________###',
  '########sssss###qqqqqqqqqqqq######....sssssssssssssssssssssss###',
  '########sssss##############Q######....ss0s^ssssssssssssssssss###',
  '########sssss#####################....ssssssssssssssssss/ssss###',
  '########sssss#####################....sssssssssssssssssssss7s###',
  '########sssss#####################..n.ssssssss/Rsssssssssssss###',
  '########sssss#####################....sssssssssssssssssssssss###',
  '#######Jsssss####A##########################sssss###############',
  '########sssss##]###[o##U#]######]]##]##]##[osssss#]#############',
  '########sssssqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqsssssqqqqq##########',
  '########sssssqqqqqqqqqqqqqqkqqqqqqqqqqqqqqqqqqqqqqqqqq##########',
  '########sssssqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq7qq##########',
  '########sssssqssssssssssssssssssssskpsssssssssssssqqqq##########',
  '##########qqqqssssssssssssssssssssssssssRsssssssssqqqq##########',
  '##########qqqqssssssssssssssssssssssssssssssssssssqqqq##########',
  '##########qqqqssss;sssssxsqqqqqqqqqqqqsssssss;ssssqqqq##########',
  '##########qqqqssssssssssssqqqqqqqqqqqqssssssssssssqqqq##########',
  '#########oqqqqssssssssssssqqqqqqqqqqqqssssssssssssqqqq##########',
  '##########qqqqssssssssssssqqqqhhhhqqqqsssssssssscsqqqq##########',
  '##########qqqqsssssssspsssqqqqh)hhqqqqssssssssssbsqxqqo#########',
  '#######J##qqqqssssssssssssqqqqhhhhqqqqssssssssssssqqqq##########',
  '##########qqqqssssssssssssqqqqqqqqqqqqssspssssssssqqqq##########',
  '##########qqqqssssssssssssqqqqqqqqqqqqssssssssssssqqqq##########',
  '##########qqqqssssssssssssqqqqqqqqqqqqssssssssssssqqqq##########',
  '##########kqqqstssssssssssqqqqqqqqqqqqssssssssskssqqqq######Q###',
  '#######J##qqqqssssssssss2sssssssssxsssssssssssssssqqqq######J###',
  '##########qqqqssssssssssssssssssssssksssssssssssssqqqq#######A##',
  '##########qqkqssss;xsssssssssssssssssssssssss;ssssqqqq##########',
  '##########qqqqssssssssssssspsssssssssssssxssssssssqqqq##########',
  '##########qqqkssssssssssssssssssssssssssssssssssssqqqq##########',
  '##########qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq##########',
  '##########qq7qqqkqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq7qq########A#',
  '##########qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq##J#######',
  '##Q#########################ssssssss#######################J####',
  '############################ssssssss############################',
  '############################ssssssss############################',
  '############################ssssssss############################',
  '############################ssssssss############################',
  '#########J###########J######ssssssss############################',
  '############################ssssssss########Q###################',
  '############################ssssssss############################',
];

/** Крюки: столб (x, y) → кольцо (tx, ty), местные координаты района. */
export const F13_HOOKS: Record<string, [number, number, number, number][]> = {
  f13: [
    [48, 65, 54, 65],
    [53, 63, 47, 63],
    [31, 97, 31, 88],
    [34, 87, 34, 96],
    [44, 97, 43, 93],
    [46, 93, 47, 88],
    [45, 87, 44, 92],
    [42, 91, 46, 96],
  ],
  f13wall: [
    [15, 67, 15, 58],
    [16, 58, 16, 67],
    [35, 67, 35, 58],
    [36, 58, 36, 67],
    [54, 67, 54, 58],
    [55, 58, 55, 67],
  ],
  f13bell: [
    [40, 73, 42, 66],
    [44, 64, 50, 59],
    [52, 56, 55, 51],
    [57, 51, 52, 58],
    [49, 57, 44, 65],
    [41, 64, 42, 73],
    [53, 58, 57, 61],
    [58, 62, 53, 59],
  ],
};
