// Карта района «Ядро» этажа 15 — собрана скриптом scripts/dungeon/f15_boss.py
// (кисти brush.py). Руками не править: запустите скрипт, он перепишет файл.
// Нижний ряд — стык с «Миром»: пол ровно в столбцах F15_JOIN (28–35).

/** Геометрия района: центр арены и звезды, радиус арены, ворота, зал. */
export const F15B_GEO = {
  cx: 31.5,
  cy: 29.5,
  r: 13.0,
  gateY: 43,
  hall: { x0: 15, y0: 44, x1: 48, y1: 55 },
  rows: 104,
} as const;

export const F15_HEART_MAP: string[] = [
  '################################################################',
  '##########################WWWWWWWWWW############################',
  '#########################WWWWWQWWWWWW###########################',
  '########################WWWQwwwwwwWWWWW#########################',
  '########################WWWwwxwwwxwWQWW#########################',
  '########################WWwwwwwwwwwwwWW#########################',
  '########################WWwxwww>wwwxwWW#########################',
  '########################WWwwwwwwwwwwwWW#########################',
  '########################WWWwwwwwwwwwWWW#########################',
  '########################WWWWWwwwwWWWWWW#########################',
  '#########################WWWWWwwwWWWWW##########################',
  '###########################WWWwwwWW#############################',
  '############################WWwwwWW#############################',
  '############################WWSSSWW#############################',
  '############################WWfffWW#############################',
  '########################WWWWWWfffWWWWWW#########################',
  '#######################WWWWWRWfffWQWWWWW########################',
  '#####################WWWWQfffffffffffRWWWW######################',
  '####################WWWWWfffffffffffffWWWWW#####################',
  '###################WWWRffffgffftfffgffffQWWW####################',
  '###################WWWffftfffffffffffftffWWW####################',
  '##################WWWfffffffffffffffffffffWWW###################',
  '#################WWWWff555fffffffffff666fxWWWW##################',
  '#################WWQfff515fffffffffff626fffRWW##################',
  '#################WWfxff555fffffffffff666ffffWW##################',
  '#################WWtfgfffffffffffffffffffgffWW##################',
  '#################WWfffffffffffqqqfffffffffffWW##################',
  '################WWWffffffffffqqqqqffffffffffWWW#################',
  '################WWWfffffffffqqqqqqqfffffffffWWW#################',
  '################WWfffftfffffqqqFqqqfffffftfffWW#################',
  '################WWWfffffffffqqqqqqqfffffffffWWW#################',
  '################WWWffffffffffqqKqqffffffffffWWW#################',
  '#################WWfffffffffffqqqfffffffffffWW##################',
  '#################WWffgfffffffffffffffffffgffWW##################',
  '#################WWfffffffffffffffffffffffxfWW##################',
  '#################WWWfff888fffffffffff999fffWWW##################',
  '#################WWWWxf838fffffffffff949ffWWWW##################',
  '##################WWWff888fffffffffff999ffWWW###################',
  '###################WWWfffffffffffffffffffWWW####################',
  '###################WWWWffftgfffffffgftffWWWW####################',
  '####################WWWWWfffffffffffffWWWWW#####################',
  '#####################WWWWWfffffffffffWWWWW######################',
  '################WWWWWWWWWWWWWWfffWWWWWWWWWWWWWWW################',
  '###############WWWAHHNHHOHHHHHGGGHHHHHUHHZHH7HWWW###############',
  '##############WWWHhhhhhhhhhhhTjjjhhhhhhhhhhhhhHWWW##############',
  '#############WWWHhhhhhhhhhhhhhjjjhhhhhhhhhhhhhhHWWW#############',
  '#############WWHhhhhhhhhhhhhhhjjjhhhhhhhhhhhhhhhHWW#############',
  '#########WWWWWWhhhhhphhhhhphhhjjjhhhhphhhhhphhhhhWW#############',
  '#########WWWWWWhhhhhhhhhhhhhhhjjjhhhhhhhhhhhhhhhhWW#############',
  '#########WWwwwDhhehhhhhhhhhhhhjjjhhhhhhhhhhhhhehhWW#############',
  '#########WWwwwDhhhhhhhhhRhhhhhjjjhhhhhhRhhhhhhhhhWWWWWW#########',
  '#########WWwwwWhhhhhhhhhhhhhhhjjjhhhhhhhhhhhhhhhhHHWWWW#########',
  '#########WWwwwWhhhhhphhhhhphhhjjjhhhhphhhhhphhhhwwwwwWW#########',
  '#########WWwwwWWhhhhhhhhhhhhhhjjjhhhhhhhhhhhhhhhwwwwwWW#########',
  '#########WWwwwWWWhhhhhhhhhhhehjjjhhehhhhhhhhhhhWwwwwwWW#########',
  '#########WWwwwWWWWhhhhhhhhhhhhjjjhhhhhhhhhhhhhWWwwwwwWW#########',
  '#########WWwwwHHWWWWWWWWWWWWwwjjjwwwWWWWWWWWWWWWwwwwwWW#########',
  '#########WWwwwwwWWWWWWWWWWWWwwjjjwwwWWWWWWWWWWWWwwwwwWW#########',
  '#########WWWWwwwWW########WWwwjjjyywWW########WWwwwwwWW#########',
  '#########WWWWwwwWW########WWwwwwwywwWW########WWWWwwwWW#########',
  '#####WWWWWWWWwwwWW########WWwwwwwwwwWW########WWWWwwwWW#########',
  '#WWWWWWWWWQWWwwwWW########WWkyywwwwkWW##########WWwwwWW#########',
  '#WWWQWWwwyyeWwwwWW########WWwywwwwwwWW##########WWyywWW#########',
  '#WwwwWwwwwwwwwwwWW########WWwwwwwwwwWW##########WWwwwWW#########',
  '#Ww$w%wwwwwwwwwwWW########WWwwwwwwwwWW##########WWwwwWW#########',
  '#WwswWwwwwwwwwwwWW########WWwwwwwwwwWW##########WWwwwWWWWWW#####',
  '#WwwwWWwwswwwwwwWW#######WWWkwyywwwkWW#######WWWWWwwwWQWWWWW####',
  '#WWWWWWWWwWWWwwwWW#######WWWwwwywwwwWW######WWWoWWwwwwwwwWWW####',
  '#WWWWWWWWWWWWwwwWW######WWWwwwwwwwwWWW######WWQwwwwwwwwwwwWW####',
  '#######WWWWWWwwwWW######WWWwwwwwwwwWWW######WWwwwwwwwwwswwWWW###',
  '###########WWwxwWW#####WWWkwwwwwwwWWW#######WWwwwsyyywwwwwWWW###',
  '###########WWwwwWW#####WWWwwwwwwkwWWW#######WWwwwwwwwwwwwwwWW###',
  '###########WWwwwWW####WWWwwwwwwwwWWW########WWwwwwwwewwwwwwWW###',
  '###########WWwwwWW####WWQwwwwwwwwWWW########WWWwwwwwwwswwwwoW###',
  '###########WWwwwWW####WWywwwwwwwWWW#########WWWwwwwwwwwwwwwWW###',
  '###########WowyyWW####WWywwwwwwwWWW##########WWyywwwwwwwwwWWW###',
  '###########WWwwyWW####WWwwwwwwwwWWWWW########WWwwwwwswwwwWWWW###',
  '###########WWwwwWW####WWwwwwwwwwWWWWWWW######WWWswwwwwwwsWWW####',
  '###########WWwwwWW###WWWwyyywwwwyyyQWWWW#####WWWWwwyyywwyWW#####',
  '###########WWwwwWWWWWWWWWwywwwwwwywwwQWWWW####WWWwwwywwwWWW#####',
  '###########WWwwwWWWQWWWwxwwwwwwwwwwwwxQWWWWWWWWWWWwwwwwWWWW#####',
  '###########WWwwwwwyywwwwwwwwwwwwwwwwwwwwWWQWWWQWWWWWWWWWWW######',
  '###########WWyywwwwywwwwwwwwwwwewwwwwwwwyywwwwwwwwWWWWWWW#######',
  '###########WWwwwwwwwwwwwwwwwwwwwwwwwwwwwwywwwwwwwwWW############',
  '###########WWWWWWWWWWWwwwwwwwwwwwwwwyyyWwwwwwwwwwwWW############',
  '###########WWWWWWWWWWWWyywxwwwwwwwwwwxWWWWWWWWWWWWWW############',
  '####################WWWWWWwwwwwwwwwwWWWWWWWWWWWWWWWW############',
  '#####################WWWWWWWwwwwwwwyWWWW########################',
  '########################WWWWwwwwwwwyWW##########################',
  '##########################WWwwwwwwwwWW##########################',
  '##########################WWkwwwwwwkWW##########################',
  '##########################WWwwwwwwwwWW##########################',
  '##########################WowwwwwwwwWW##########################',
  '##########################WWwwwwwwwwWW##########################',
  '##########################WWwwwwwwwwWW##########################',
  '##########################WWkwwwwwwkWW##########################',
  '##########################WWywwwwwwwWW##########################',
  '##########################WWwwwwwwwwWW##########################',
  '##########################WWwwwwwwyyoW##########################',
  '##########################WWwwwwwwywWW##########################',
  '##########################WWkwwwwwwkWW##########################',
  '##########################WWwwwwwwwwWW##########################',
  '##########################WWwyywwwwwWW##########################',
  '############################wwwwwwww############################',
];
