// Этаж 8 — «Бесконечный замок». Замок, у которого нет конца: татами,
// бумажные сёдзи, раздвижные фусума, красные перила над пропастью между
// его этажами, лестницы в никуда, перевёрнутые комнаты. Комнаты здесь
// сдвигаются: перегородки ездят по пазам целыми блоками, пока играет бива.
//
// Монстры и их приём (ИИ — `f8-brains.ts`, рисунок — `f8-art.ts`):
//   • бес-прислужник — мелочь из дверей: прыжок-укус по линии, стаей;
//   • демон-мечник — серии выпадов (линия, выпад, ещё выпад), потом
//     открыт; элита режет четыре раза;
//   • многорукий — удары во все стороны разом: «звезда» конусов с
//     просветами, хватка рукой по линии;
//   • демон-паук — стреляет нитью: нить ложится на пол (вязнет), через миг
//     натягивается и режет по всей линии;
//   • фонарный дух — фонарь-обакэ, парит над пропастью, плюётся огоньками
//     веером; выдохся — опускается и открыт;
//   • демон-барабанщик — удар в боковые барабаны пускает когти по полу,
//     удар в брюхо поворачивает Барабанную (вертушка стен);
//   • бива-струнник — не дерётся: пока играет, перегородки его крыла
//     ездят; подходишь — перенесётся на другой помост; убит — комнаты
//     замирают;
//   • глазастые сёдзи — сидят в бумажной стене: глаза открываются, потом
//     сквозь бумагу бьют когти; открыты, пока руки снаружи;
//   • бес-казначей — редкий, с мешком монет, удирает сквозь двери.
// Босс — Демон семи лун (`f8boss`): четыре фазы, засечки на полосе,
// арена меняется (провалы в углах, ширмы, семь лун). Правила этажа —
// двери, перегородки, Барабанная, Перевёрнутая комната, падающий мост —
// `registerFloor(8)` в `f8-brains.ts`.
//
// Карта — `scripts/dungeon/f8.py` → `f8-map.ts` (руками не править).

import type { MobDef } from '../dungeon';
import { MAP_F8_HALLS, MAP_F8_LOWER, MAP_F8_MOON } from './f8-map';
import type { FloorDef, LegendCell, SpawnSpec } from './types';

/** Свои клетки этажа: номер вида для рисовальщика и правил этажа. */
export const F8_MARK = {
  // пол
  tatami: 1,
  blood: 2,
  scorch: 3,
  cut: 4,
  plankH: 5,
  plankV: 6,
  bridge: 7,
  bridgeFall: 8,
  ceil: 9,
  moon: 10,
  moonPit: 11,
  moonScreen: 12,
  web: 13,
  group: 14,
  ambush: 15,
  /** Паз перегородки: пол сейчас (ядро — бива Зала струны, окраина — Галереи). */
  track0: 16,
  track1: 17,
  drumFloor: 18,
  /** Пол Перевёрнутой комнаты: татами → потолок. */
  flip: 19,
  /** Там же: татами → балка потолка (стена). */
  flipBeam: 20,
  /** Под вещью — пол как у соседей. */
  inherit: 21,
  // стены
  wall: 40,
  shoji: 41,
  fusuma: 42,
  door: 43,
  red: 44,
  eyes: 45,
  window: 46,
  lamp: 47,
  shift0: 48,
  shift1: 49,
  drumWall: 50,
  /** Стена Перевёрнутой комнаты: станет полом-потолком. */
  flipWall: 51,
  /** Балка потолка: после переворота. */
  beam: 52,
  // бездна
  abyss: 60,
  abyssMoon: 61,
} as const;

/** Районы этажа. Входной — `f8` (id заготовки: на нём сохранения). */
export const F8_LOWER = 'f8';
export const F8_HALLS = 'f8halls';
export const F8_MOON = 'f8moon';

const M = F8_MARK;

const prop = (
  ref: string,
  solid: number,
  kind: 'deco' | 'breakable' = 'deco',
  hp?: number,
): LegendCell['obj'] => ({ kind, ref, solid, hp });

/** Свои буквы карты — одни на все районы (см. шапку `scripts/dungeon/f8.py`). */
const LEGEND: Record<string, LegendCell> = {
  // --- пол
  ':': { tile: 'floor', mark: M.tatami },
  ';': { tile: 'floor', mark: M.blood },
  '*': { tile: 'floor', mark: M.scorch },
  x: { tile: 'floor', mark: M.cut },
  '-': { tile: 'floor', mark: M.plankH },
  '|': { tile: 'floor', mark: M.plankV },
  '+': { tile: 'floor', mark: M.bridge },
  '}': { tile: 'floor', mark: M.bridgeFall },
  '^': { tile: 'floor', mark: M.ceil },
  m: { tile: 'floor', mark: M.moon },
  n: { tile: 'floor', mark: M.moonPit },
  u: { tile: 'floor', mark: M.moonScreen },
  // Паутина: вязнет, в ней сидят пауки.
  w: { tile: 'hazard', mark: M.web, hazard: { slow: 0.55 } },
  r: { tile: 'floor', mark: M.group },
  A: { tile: 'floor', mark: M.ambush },
  z: { tile: 'floor', mark: M.track0 },
  ']': { tile: 'floor', mark: M.track1 },
  q: { tile: 'floor', mark: M.drumFloor },
  F: { tile: 'floor', mark: M.flip },
  j: { tile: 'floor', mark: M.flipBeam },
  // --- стены
  W: { tile: 'wall', mark: M.wall },
  s: { tile: 'wall', mark: M.shoji, light: { r: 1.6, tint: 'warm' } },
  f: { tile: 'wall', mark: M.fusuma },
  d: { tile: 'wall', mark: M.door, obj: prop('f8_door', 0) },
  k: { tile: 'wall', mark: M.red },
  e: { tile: 'wall', mark: M.eyes, light: { r: 1.6, tint: 'warm' } },
  O: {
    tile: 'wall',
    mark: M.window,
    obj: prop('f8_moonwin', 0),
    light: { r: 4.2, tint: 'cold' },
  },
  h: {
    tile: 'wall',
    mark: M.lamp,
    obj: prop('f8_wlamp', 0),
    light: { r: 4.6, tint: 'warm' },
  },
  Z: { tile: 'wall', mark: M.shift0 },
  '[': { tile: 'wall', mark: M.shift1 },
  Q: { tile: 'wall', mark: M.drumWall },
  J: { tile: 'wall', mark: M.flipWall },
  // --- бездна
  '0': { tile: 'deep', mark: M.abyss },
  '9': { tile: 'deep', mark: M.abyssMoon, light: { r: 1.2, tint: 'violet' } },
  '2': {
    tile: 'deep',
    mark: M.abyssMoon,
    obj: prop('f8_float', 0),
    light: { r: 2.6, tint: 'warm' },
  },
  // --- вещи на полу (пол под ними — как у соседей)
  t: {
    tile: 'floor',
    mark: M.inherit,
    obj: prop('f8_andon', 0.26),
    light: { r: 3.6, tint: 'warm' },
  },
  g: {
    tile: 'floor',
    mark: M.inherit,
    obj: prop('f8_toro', 0.34),
    light: { r: 3.4, tint: 'warm' },
  },
  i: { tile: 'floor', mark: M.inherit, obj: prop('f8_incense', 0.28) },
  y: {
    tile: 'floor',
    mark: M.inherit,
    obj: prop('f8_candles', 0.2),
    light: { r: 2.6, tint: 'warm' },
  },
  p: { tile: 'floor', mark: M.inherit, obj: prop('f8_byobu', 0.36, 'breakable', 2) },
  H: { tile: 'floor', mark: M.inherit, obj: prop('f8_sake', 0.36, 'breakable', 2) },
  V: { tile: 'floor', mark: M.inherit, obj: prop('f8_table', 0.34, 'breakable', 1) },
  U: { tile: 'floor', mark: M.inherit, obj: prop('f8_vase', 0.26, 'breakable', 1) },
  I: { tile: 'floor', mark: M.inherit, obj: prop('f8_armor', 0.34) },
  '8': { tile: 'floor', mark: M.inherit, obj: prop('f8_rack', 0.3) },
  '7': { tile: 'floor', mark: M.inherit, obj: prop('f8_taiko', 0.4) },
  // Помосты бивы: `6` — Зала струны (ядро), `&` — Галереи доспехов (окраина).
  '6': { tile: 'floor', mark: M.inherit, obj: prop('f8_stage', 0) },
  '&': { tile: 'floor', mark: M.inherit, obj: prop('f8_stage2', 0) },
  '5': { tile: 'floor', mark: M.drumFloor, obj: prop('f8_drumseat', 0) },
  '4': { tile: 'floor', mark: M.inherit, obj: prop('f8_stairs', 0.44) },
  '3': { tile: 'floor', mark: M.inherit, obj: prop('f8_stairs_up', 0.44) },
  '/': { tile: 'floor', mark: M.inherit, obj: prop('f8_cushion', 0) },
  // Лампа потолка Перевёрнутой комнаты: видна только после переворота.
  '(': { tile: 'floor', mark: M.flip, obj: prop('f8_c_lamp', 0.24) },
  // Лампа, висящая «вверх» (перевёрнутые спальни: ходишь по потолку).
  ')': {
    tile: 'floor',
    mark: M.ceil,
    obj: prop('f8_uplamp', 0.24),
    light: { r: 3.2, tint: 'warm' },
  },
};

// Рост силы от этажа 5: этаж 6 ≈ этаж 5, дальше +15% за этаж (библия §12б).
// Уровень районов — 9, как верх этажа 5, поэтому числа — ×1,32 к пятому.
const MOBS: MobDef[] = [
  {
    id: 'f8_imp',
    name: 'Бес-прислужник',
    many: 'бесов-прислужников',
    hp: 9,
    dmg: 9,
    speed: 3.9,
    radius: 0.24,
    windup: 0.42,
    reach: 0.3,
    rest: 0.8,
    xp: 3,
    meat: ['f8_onigiri', 0.35, 1],
    mats: [['f8mat', 0.18]],
    beast: true,
    brain: 'f8_imp',
    art: { kind: 'paint', id: 'f8_imp' },
    mass: 0.8,
    flinch: 0.6,
    eye: '#ffd040',
    gore: ['#6a2a2a', '#c9453a', '#2a1a1a'],
  },
  {
    id: 'f8_blade',
    name: 'Демон-мечник',
    many: 'демонов-мечников',
    hp: 21,
    dmg: 13,
    speed: 3.5,
    radius: 0.3,
    windup: 0.5,
    reach: 0.55,
    rest: 0.9,
    xp: 8,
    meat: null,
    mats: [
      ['f8_horn', 0.28],
      ['f8mat', 0.12],
    ],
    beast: true,
    brain: 'f8_blade',
    art: { kind: 'paint', id: 'f8_blade' },
    mass: 1.4,
    flinch: 0.3,
    eye: '#ff5040',
    gore: ['#3a2a44', '#c9453a', '#d8d0c0'],
  },
  {
    id: 'f8_arms',
    name: 'Многорукий',
    many: 'многоруких',
    hp: 50,
    dmg: 15,
    speed: 2.1,
    radius: 0.5,
    windup: 0.8,
    reach: 0.7,
    rest: 1.2,
    xp: 14,
    meat: ['f8_mochi', 0.45, 1],
    mats: [['f8mat', 0.35]],
    beast: true,
    brain: 'f8_arms',
    art: { kind: 'paint', id: 'f8_arms' },
    mass: 5,
    flinch: 0,
    stunT: 0.1,
    eye: '#ff8a30',
    gore: ['#5a6a3a', '#a03a2a', '#2a3018'],
  },
  {
    id: 'f8_spider',
    name: 'Демон-паук',
    many: 'демонов-пауков',
    hp: 17,
    dmg: 11,
    speed: 3.4,
    radius: 0.34,
    windup: 0.45,
    reach: 0.4,
    rest: 0.9,
    xp: 7,
    meat: ['f8_spiderleg', 0.5, 1],
    mats: [['f8_silk', 0.4]],
    beast: true,
    brain: 'f8_spider',
    art: { kind: 'paint', id: 'f8_spider' },
    mass: 1.3,
    flinch: 0.4,
    eye: '#ff3a8a',
    gore: ['#e8e4f0', '#6a2a5a', '#1a1420'],
  },
  {
    id: 'f8_lantern',
    name: 'Фонарный дух',
    many: 'фонарных духов',
    hp: 14,
    dmg: 11,
    speed: 2.4,
    radius: 0.32,
    windup: 0.6,
    reach: 0.3,
    rest: 1,
    xp: 7,
    meat: null,
    mats: [['f8_paper', 0.45]],
    beast: true,
    brain: 'f8_lantern',
    art: { kind: 'paint', id: 'f8_lantern' },
    mass: 0.7,
    flinch: 0.5,
    fly: true,
    light: 3,
    eye: '#ffe070',
    gore: ['#f0e0b0', '#ff9a30', '#a02a1a'],
    shot: {
      speed: 5.2,
      r: 0.26,
      life: 2.2,
      dmg: 0.9,
      art: 'f8_wisp',
      status: 'burn',
      dur: 1.4,
      n: 3,
      spread: 0.6,
    },
  },
  {
    id: 'f8_drum',
    name: 'Демон-барабанщик',
    many: 'демонов-барабанщиков',
    hp: 44,
    dmg: 14,
    speed: 1.9,
    radius: 0.46,
    windup: 0.7,
    reach: 0.5,
    rest: 1.1,
    xp: 16,
    meat: ['f8_mochi', 0.5, 1],
    mats: [
      ['f8mat', 0.4],
      ['f8_horn', 0.2],
    ],
    beast: true,
    brain: 'f8_drum',
    art: { kind: 'paint', id: 'f8_drum' },
    mass: 4,
    flinch: 0.1,
    eye: '#ffb040',
    gore: ['#7a3a2a', '#c9453a', '#e8d8b0'],
  },
  {
    id: 'f8_biwa',
    name: 'Бива-струнник',
    many: 'бива-струнников',
    hp: 30,
    dmg: 1,
    speed: 2.2,
    radius: 0.32,
    windup: 0.6,
    reach: 0.3,
    rest: 1,
    xp: 18,
    meat: null,
    mats: [['f8_string', 0.85]],
    beast: true,
    brain: 'f8_biwa',
    art: { kind: 'paint', id: 'f8_biwa' },
    mass: 1.2,
    flinch: 0.2,
    noAlbino: true,
    eye: '#e0c8ff',
    gore: ['#2a2230', '#c9453a', '#e8e0f0'],
  },
  {
    id: 'f8_eyes',
    name: 'Глазастые сёдзи',
    many: 'глазастых сёдзи',
    hp: 19,
    dmg: 13,
    speed: 0.01,
    radius: 0.34,
    windup: 0.9,
    reach: 0.4,
    rest: 1.2,
    xp: 8,
    meat: null,
    mats: [['f8_paper', 0.3]],
    beast: true,
    brain: 'f8_eyes',
    art: { kind: 'paint', id: 'f8_eyes' },
    mass: 50,
    flinch: 0,
    stunT: 0.05,
    noAlbino: true,
    eye: '#ff2a2a',
    gore: ['#f0e8d0', '#3a1a1a', '#c9453a'],
  },
  {
    id: 'f8_miser',
    name: 'Бес-казначей',
    many: 'бесов-казначеев',
    hp: 24,
    dmg: 1,
    speed: 4.1,
    radius: 0.3,
    windup: 0.5,
    reach: 0.3,
    rest: 1,
    xp: 12,
    meat: ['f8_onigiri', 1, 2],
    mats: [],
    beast: true,
    brain: 'f8_miser',
    art: { kind: 'paint', id: 'f8_miser' },
    mass: 1.1,
    flinch: 0.5,
    coins: 420,
    resume: 'flee',
    eye: '#ffe040',
    gore: ['#ffd84a', '#c9453a', '#6a4a2a'],
  },
  {
    id: 'f8boss',
    name: 'Демон семи лун',
    many: 'Демон семи лун',
    hp: 640,
    dmg: 16.5,
    speed: 3,
    radius: 0.62,
    windup: 0.8,
    reach: 0.9,
    rest: 0.9,
    xp: 800,
    meat: null,
    mats: [],
    beast: true,
    brain: 'f8boss',
    art: { kind: 'paint', id: 'f8boss' },
    mass: 9,
    boss: true,
    noAlbino: true,
    eye: '#ffd84a',
    gore: ['#2a1a3a', '#c9453a', '#ffe8a0'],
  },
  {
    // Луна финала: не бьётся и не считается — светит и пускает полумесяцы.
    id: 'f8_moon',
    name: 'Луна',
    many: 'лун',
    hp: 1,
    dmg: 18,
    speed: 0,
    radius: 0.3,
    windup: 0.6,
    reach: 0.3,
    rest: 1,
    xp: 0,
    meat: null,
    mats: [],
    beast: false,
    brain: 'f8_moon',
    art: { kind: 'paint', id: 'f8_moon' },
    mass: 99,
    fly: true,
    light: 3.4,
    noAlbino: true,
    eye: '#fff0b0',
  },
];

/** Кто водится в Нижних покоях: выходят из дверей, падают со свода. */
const spawnLower: SpawnSpec = {
  mobs: [
    ['f8_imp', 42],
    ['f8_blade', 30],
    ['f8_spider', 20],
    ['f8_arms', 8],
  ],
  density: 0.8,
  pack: [1, 2],
  filler: 'f8_imp',
  group: (i) => (i === 0 ? 'f8_blade' : 'f8_imp'),
  horde: null,
  treasure: 'f8_miser',
  nest: () => 'f8_imp',
};

const spawnHalls: SpawnSpec = {
  mobs: [
    ['f8_blade', 38],
    ['f8_imp', 30],
    ['f8_arms', 20],
    ['f8_spider', 12],
  ],
  density: 0.85,
  pack: [1, 2],
  filler: 'f8_imp',
  group: (i) => (i === 0 ? 'f8_arms' : 'f8_blade'),
  horde: null,
  treasure: 'f8_miser',
  nest: () => 'f8_imp',
};

const spawnMoon: SpawnSpec = {
  mobs: [
    ['f8_blade', 36],
    ['f8_lantern', 30],
    ['f8_arms', 16],
    ['f8_spider', 18],
  ],
  density: 0.9,
  pack: [1, 2],
  filler: 'f8_blade',
  group: (i) => (i === 0 ? 'f8_arms' : 'f8_blade'),
  horde: null,
  treasure: 'f8_miser',
  nest: () => 'f8_lantern',
};

export const F8: FloorDef = {
  id: 8,
  name: 'Бесконечный замок',
  lead: 'Татами, сёдзи и пропасть между этажами. Комнаты сдвигаются под звон бивы.',
  mapVer: 2,
  areas: [
    {
      id: F8_LOWER,
      name: 'Нижние покои',
      lead: 'Двери скользят сами. За бумагой кто-то смотрит.',
      tier: 8,
      level: 9,
      ambient: 0.44,
      rows: MAP_F8_LOWER,
      skin: {
        floor: 'slab',
        wall: 'brick',
        tint: { mul: [1.02, 0.9, 0.84], mix: '#5a2a1a', k: 0.1 },
        fog: '#0b0707',
      },
      legend: LEGEND,
      mine: 'f8mine',
      spawn: spawnLower,
    },
    {
      id: F8_HALLS,
      name: 'Сдвигающиеся залы',
      lead: 'Звенит струна — и стены едут. Найди того, кто играет.',
      tier: 8,
      level: 9,
      ambient: 0.38,
      rows: MAP_F8_HALLS,
      skin: {
        floor: 'slab',
        wall: 'brick',
        tint: { mul: [0.9, 0.84, 1.02], mix: '#3a2458', k: 0.14 },
        fog: '#08060e',
      },
      legend: LEGEND,
      mine: 'f8mine',
      spawn: spawnHalls,
    },
    {
      id: F8_MOON,
      name: 'Зал луны',
      lead: 'Мосты над пропастью. Где-то наверху семь лун.',
      tier: 8,
      level: 9,
      ambient: 0.34,
      rows: MAP_F8_MOON,
      skin: {
        floor: 'slab',
        wall: 'brick',
        tint: { mul: [0.86, 0.88, 1.06], mix: '#2a3060', k: 0.16 },
        fog: '#05060d',
      },
      legend: LEGEND,
      mine: 'f8mine2',
      spawn: spawnMoon,
    },
  ],
  boss: {
    id: 'f8boss',
    name: 'Демон семи лун',
    lead: 'Арена под лунным окном',
    area: F8_MOON,
    restMs: 20 * 60_000,
    mob: 'f8boss',
    script: 'f8boss',
    parts: ['f8boss'],
    loot: (rnd) => ({
      tokens: 55 + Math.floor(rnd() * 35),
      keys: rnd() < 0.65 ? 1 : 0,
      coins: 55_000,
      mats: {
        f8_moonblade: 1,
        f8_horn: 2 + Math.floor(rnd() * 3),
        f8mat: 3 + Math.floor(rnd() * 4),
      },
    }),
  },
  mines: [
    {
      id: 'f8mine',
      name: 'Шахта под кладовой',
      area: F8_LOWER,
      windowMs: 60 * 60_000,
      ores: [14, 15],
      share: [0.22, 0.29, 0.36, 0.44, 0.52],
      pyrite: 0,
      blocks: 1.7,
    },
    {
      id: 'f8mine2',
      name: 'Шахта на острове',
      area: F8_MOON,
      windowMs: 3 * 60 * 60_000,
      ores: [14, 15],
      share: [0.28, 0.36, 0.44, 0.52, 0.6],
      pyrite: 0,
      blocks: 2.4,
    },
  ],
  mobs: MOBS,
  meats: [
    { id: 'f8_onigiri', name: 'Рисовый колобок', price: 26, heal: 0.2 },
    { id: 'f8_spiderleg', name: 'Паучья лапа', price: 22, heal: 0.16 },
    { id: 'f8_mochi', name: 'Лунный моти', price: 48, heal: 0.3 },
  ],
  mats: [
    {
      id: 'f8mat',
      name: 'Лаковая щепа',
      price: 300,
      lead: 'Щепа от ширм и перил замка. Красный лак ещё блестит.',
    },
    {
      id: 'f8_horn',
      name: 'Рог мечника',
      price: 340,
      lead: 'Короткий чёрный рог. Твёрже стали, которой он рубил.',
    },
    {
      id: 'f8_silk',
      name: 'Паучья нить',
      price: 280,
      lead: 'Моток нити демона-паука. Режет, если натянуть.',
    },
    {
      id: 'f8_paper',
      name: 'Фонарная бумага',
      price: 260,
      lead: 'Промасленная бумага фонарного духа. Тёплая на ощупь.',
    },
    {
      id: 'f8_string',
      name: 'Струна бивы',
      price: 900,
      lead: 'Шёлковая струна. Тронешь — где-то сдвигается стена.',
    },
    {
      id: 'f8_moonblade',
      name: 'Клинок семи лун',
      price: 40_000,
      lead: 'Трофей. Лезвие в глазах, и все они закрыты.',
      stack: 1,
    },
  ],
  music: { explore: 'depths', boss: 'boss' },
  cover: '/ui/areas/f8.png',
};
