// Этаж 9 — «Лабиринт гидры». Затопленные руины, болото и корни, круги-
// телепорты, которые переносят в пару (пара — по цвету и руне; часть кругов
// — ловушки), а в чёрной заводи на дне — многоглавая гидра.
//
// Монстры и их приём (ИИ — `f9-brains.ts`, рисунок — `f9-art.ts`):
//   • ящеролюд-копейщик — держит дистанцию копья, выпад по линии; в трясине
//     не вязнет, а бежит быстрее;
//   • ядовитая жаба — плевок навесом, на месте падения — лужа яда; сидя в
//     ядовитой топи, плюётся очередью;
//   • телепорт-кобольд — прыгает за спину (короткая метка), убегает прыжком;
//     ходит кругами-телепортами, как ты;
//   • каменный змей — взгляд конусом: замедляет, второй взгляд подряд —
//     каменеешь (оглушение); за стеной не достанет;
//   • болотный огонь — светится и заманивает к воде, вспыхивает холодом;
//   • корневая хваталка — живёт только в трясине: под водой невидима,
//     вокруг героя — круг корней (держат), потом открыта и хлещет;
//   • пиявка — выпрыгивает из воды, присасывается (пьёт кровь), рывок
//     стряхивает;
//   • ящер-жрец — рисует под героем руну: не вышел — перенесён к жрецу, в
//     кольцо ящеров;
//   • кобольд-скупщик — редкий, с мешком монет: убегает кругами и прыжками.
// Босс — многоглавая гидра (`f9boss`, тело) с головами-частями (`f9_head`)
// и скрытой головой (`f9_crown`); срубленная голова отрастает двумя, если
// шею не прижечь огнём жаровни (`f9_stump`). Правила этажа — круги,
// корневая часовня, круговорот, прилив на гати — `registerFloor(9)`.
//
// Карта — `scripts/dungeon/f9.py` → `f9-map.ts` (руками не править).

import type { MobDef } from '../dungeon';
import { MAP_F9_LAIR, MAP_F9_MAZE, MAP_F9_RUINS } from './f9-map';
import type { FloorDef, HazardSpec, LegendCell, SpawnSpec } from './types';

/** Свои клетки этажа: номер вида для рисовальщика и правил этажа. */
export const F9_MARK = {
  water: 1,
  bog: 2,
  venom: 3,
  roots: 4,
  moss: 5,
  mosaic: 6,
  vinewall: 7,
  rootwall: 8,
  glowmoss: 9,
  pool: 10,
  mud: 11,
  chapel: 12,
  causeway: 13,
  sunk: 14,
  hall: 15,
  ambush: 16,
  flood: 17,
  lily: 18,
  reeds: 19,
  eggs: 20,
  /** Круги: пара k (1…9) — 20 + k; ловушка, выход из засады. */
  ring: 20,
  trap: 30,
  back: 31,
} as const;

/** Номер вида клетки круга пары k (1…9). */
export const ringMark = (k: number) => F9_MARK.ring + k;
/** Круг ли это (любой: пара, ловушка, выход). */
export const isRingMark = (mk: number) => mk > F9_MARK.ring && mk <= F9_MARK.back;
/** Вода топи (с кувшинками — тоже вода). */
export const isWaterMark = (mk: number) =>
  mk === F9_MARK.water || mk === F9_MARK.lily || mk === F9_MARK.sunk;
/** Трясина (с камышом и икрой — тоже). */
export const isBogMark = (mk: number) =>
  mk === F9_MARK.bog || mk === F9_MARK.reeds || mk === F9_MARK.eggs || mk === F9_MARK.flood;

/** Районы этажа. Входной — `f9` (id заготовки: на нём могут стоять сохранения). */
export const F9_RUINS = 'f9';
export const F9_MAZE = 'f9maze';
export const F9_LAIR = 'f9lair';

const M = F9_MARK;

/** Трясина: вязнет, но не травит. В ней живут корни, ящеры в ней быстрее. */
export const BOG: HazardSpec = { slow: 0.72 };
/** Ядовитая топь: травит, пока стоишь, и ещё немного после. */
export const VENOM: HazardSpec = { status: 'poison', dur: 1.4, slow: 0.82 };

const ringCell = (k: number, light: LegendCell['light'] | undefined): LegendCell => ({
  tile: 'floor',
  mark: ringMark(k),
  obj: { kind: 'deco', ref: 'f9_ring', solid: 0 },
  light,
});

/** Свои буквы карты — одни на все районы (см. шапку `scripts/dungeon/f9.py`). */
const LEGEND: Record<string, LegendCell> = {
  w: { tile: 'deep', mark: M.water },
  e: { tile: 'deep', mark: M.lily, obj: { kind: 'deco', ref: 'f9_lily', solid: 0 } },
  '"': { tile: 'hazard', mark: M.bog, hazard: BOG },
  y: {
    tile: 'hazard',
    mark: M.reeds,
    hazard: BOG,
    obj: { kind: 'deco', ref: 'f9_reeds', solid: 0 },
  },
  d: {
    tile: 'hazard',
    mark: M.eggs,
    hazard: BOG,
    obj: { kind: 'breakable', ref: 'f9_eggs', solid: 0.26, hp: 1, loot: 'f9_toxin' },
  },
  ';': { tile: 'hazard', mark: M.venom, hazard: VENOM, light: { r: 1.4, tint: 'green' } },
  m: { tile: 'floor', mark: M.moss },
  q: { tile: 'floor', mark: M.mosaic },
  r: { tile: 'floor', mark: M.roots },
  s: { tile: 'floor', mark: M.chapel },
  J: { tile: 'floor', mark: M.hall },
  N: { tile: 'floor', mark: M.ambush },
  '^': { tile: 'floor', mark: M.causeway },
  h: { tile: 'wall', mark: M.vinewall },
  k: { tile: 'wall', mark: M.rootwall },
  g: { tile: 'wall', mark: M.glowmoss, light: { r: 2.2, tint: 'teal' } },
  V: { tile: 'wall', mark: M.vinewall, obj: { kind: 'deco', ref: 'f9_vine', solid: 0 } },
  H: {
    tile: 'wall',
    obj: { kind: 'deco', ref: 'f9_walllamp', solid: 0 },
    light: { r: 3.8, tint: 'green' },
  },
  f: {
    tile: 'floor',
    mark: M.moss,
    obj: { kind: 'deco', ref: 'f9_shroom', solid: 0.22 },
    light: { r: 3.2, tint: 'green' },
  },
  x: {
    tile: 'floor',
    obj: { kind: 'deco', ref: 'f9_crystal', solid: 0.36 },
    light: { r: 3.4, tint: 'violet' },
  },
  j: { tile: 'floor', mark: M.mosaic, obj: { kind: 'deco', ref: 'f9_column', solid: 0.42 } },
  i: {
    tile: 'floor',
    mark: M.mosaic,
    obj: { kind: 'deco', ref: 'f9_idol', solid: 0.45 },
    light: { r: 1.6, tint: 'teal' },
  },
  p: { tile: 'floor', obj: { kind: 'breakable', ref: 'f9_urn', solid: 0.3, hp: 1 } },
  z: { tile: 'floor', mark: M.moss, obj: { kind: 'deco', ref: 'f9_log', solid: 0.4 } },
  Q: { tile: 'floor', obj: { kind: 'deco', ref: 'f9_bones', solid: 0 } },
  t: { tile: 'floor', obj: { kind: 'deco', ref: 'f9_totem', solid: 0.3 } },
  A: {
    tile: 'floor',
    obj: { kind: 'deco', ref: 'f9_runestone', solid: 0.45 },
    light: { r: 3, tint: 'violet' },
  },
  F: {
    tile: 'floor',
    mark: M.moss,
    obj: { kind: 'deco', ref: 'f9_brazier', solid: 0.42 },
    light: { r: 4.4, tint: 'warm' },
  },
  O: { tile: 'deep', mark: M.pool },
  // Круги: пары 1…4, Круговорот 5…8, точка выхода из засады 9.
  '1': ringCell(1, { r: 2.4, tint: 'violet' }),
  '2': ringCell(2, { r: 2.4, tint: 'violet' }),
  '3': ringCell(3, { r: 2.4, tint: 'violet' }),
  '4': ringCell(4, { r: 2.4, tint: 'violet' }),
  '5': ringCell(5, { r: 2.4, tint: 'violet' }),
  '6': ringCell(6, { r: 2.4, tint: 'violet' }),
  '7': ringCell(7, { r: 2.4, tint: 'violet' }),
  '8': ringCell(8, { r: 2.4, tint: 'violet' }),
  '9': ringCell(9, undefined),
  Z: {
    tile: 'floor',
    mark: M.trap,
    obj: { kind: 'deco', ref: 'f9_ring', solid: 0 },
    light: { r: 2.2, tint: 'violet' },
  },
  '0': {
    tile: 'floor',
    mark: M.back,
    obj: { kind: 'deco', ref: 'f9_ring', solid: 0 },
    light: { r: 2.4, tint: 'teal' },
  },
};

const GORE_LIZARD = ['#3e7a4a', '#b8c060', '#1e3a24'];

const MOBS: MobDef[] = [
  {
    id: 'f9_lizard',
    name: 'Ящеролюд-копейщик',
    many: 'ящеролюдов',
    hp: 30,
    dmg: 14,
    speed: 2.9,
    radius: 0.32,
    windup: 0.45,
    reach: 0.5,
    rest: 0.8,
    xp: 8,
    meat: ['f9_tail', 0.45, 1],
    mats: [['f9mat', 0.35]],
    beast: true,
    brain: 'f9_lizard',
    art: { kind: 'paint', id: 'f9_lizard' },
    mass: 1.6,
    flinch: 0.3,
    eye: '#ffd23a',
    gore: GORE_LIZARD,
  },
  {
    id: 'f9_toad',
    name: 'Ядовитая жаба',
    many: 'ядовитых жаб',
    hp: 20,
    dmg: 10,
    speed: 2.1,
    radius: 0.3,
    windup: 0.4,
    reach: 0.35,
    rest: 1,
    xp: 6,
    meat: ['f9_frogleg', 0.55, 1],
    mats: [['f9_toxin', 0.3]],
    beast: true,
    brain: 'f9_toad',
    art: { kind: 'paint', id: 'f9_toad' },
    mass: 1.3,
    flinch: 0.5,
    eye: '#ff9a2a',
    gore: ['#6a7a2a', '#e08a2a', '#2e3a12'],
    shot: {
      speed: 6,
      r: 0.42,
      life: 2,
      dmg: 0.85,
      art: 'f9_spit',
      status: 'poison',
      dur: 2.4,
      lob: true,
    },
  },
  {
    id: 'f9_kobold',
    name: 'Телепорт-кобольд',
    many: 'телепорт-кобольдов',
    hp: 14,
    dmg: 11,
    speed: 3.7,
    radius: 0.25,
    windup: 0.32,
    reach: 0.4,
    rest: 0.7,
    xp: 6,
    meat: null,
    mats: [['f9_rune', 0.25]],
    beast: true,
    brain: 'f9_kobold',
    art: { kind: 'paint', id: 'f9_kobold' },
    mass: 0.9,
    flinch: 0.45,
    eye: '#7af0ff',
    gore: ['#6a4a8a', '#c8a0ff', '#3a2a4a'],
  },
  {
    id: 'f9_serpent',
    name: 'Каменный змей',
    many: 'каменных змеев',
    hp: 38,
    dmg: 12,
    speed: 2,
    radius: 0.34,
    windup: 0.5,
    reach: 0.45,
    rest: 1,
    xp: 9,
    meat: ['f9_snake', 0.4, 1],
    mats: [['f9mat', 0.25]],
    beast: true,
    brain: 'f9_serpent',
    art: { kind: 'paint', id: 'f9_serpent' },
    mass: 2.2,
    flinch: 0.2,
    eye: '#6affe0',
    gore: ['#5a6660', '#9aa89e', '#2a3430'],
  },
  {
    id: 'f9_wisp',
    name: 'Болотный огонь',
    many: 'болотных огней',
    hp: 11,
    dmg: 9,
    speed: 2.6,
    radius: 0.26,
    windup: 0.6,
    reach: 0.3,
    rest: 1,
    xp: 7,
    meat: null,
    mats: [['f9_mana', 0.3]],
    beast: true,
    brain: 'f9_wisp',
    art: { kind: 'paint', id: 'f9_wisp' },
    mass: 0.5,
    flinch: 0.6,
    fly: true,
    light: 2.6,
    eye: '#c8fff0',
    gore: ['#8affd8', '#e8fff8', '#2a8a7a'],
  },
  {
    id: 'f9_root',
    name: 'Корневая хваталка',
    many: 'корневых хваталок',
    hp: 28,
    dmg: 10,
    speed: 3.2,
    radius: 0.36,
    windup: 0.5,
    reach: 0.6,
    rest: 1,
    xp: 8,
    meat: null,
    mats: [['f9_root', 0.4]],
    beast: true,
    brain: 'f9_root',
    art: { kind: 'paint', id: 'f9_root' },
    mass: 4,
    flinch: 0.25,
    stunT: 0.3,
    eye: '#ffb040',
    gore: ['#4a3420', '#8a6a3a', '#2a1a0e'],
  },
  {
    id: 'f9_leech',
    name: 'Пиявка',
    many: 'пиявок',
    hp: 6,
    dmg: 5,
    speed: 3.4,
    radius: 0.2,
    windup: 0.3,
    reach: 0.2,
    rest: 1.1,
    xp: 3,
    meat: null,
    mats: [],
    beast: true,
    brain: 'f9_leech',
    art: { kind: 'paint', id: 'f9_leech' },
    mass: 0.4,
    flinch: 1,
    eye: '#ff4a6a',
    gore: ['#3a1a24', '#a82a3a', '#1a0a10'],
  },
  {
    id: 'f9_priest',
    name: 'Ящер-жрец',
    many: 'ящеров-жрецов',
    hp: 18,
    dmg: 9,
    speed: 2.7,
    radius: 0.3,
    windup: 0.4,
    reach: 0.4,
    rest: 1,
    xp: 10,
    meat: ['f9_tail', 0.3, 1],
    mats: [
      ['f9_rune', 0.45],
      ['f9_mana', 0.15],
    ],
    beast: true,
    brain: 'f9_priest',
    art: { kind: 'paint', id: 'f9_priest' },
    mass: 1.2,
    flinch: 0.6,
    eye: '#c89aff',
    gore: GORE_LIZARD,
  },
  {
    id: 'f9_hoarder',
    name: 'Кобольд-скупщик',
    many: 'кобольдов-скупщиков',
    hp: 22,
    dmg: 6,
    speed: 3.9,
    radius: 0.28,
    windup: 0.4,
    reach: 0.3,
    rest: 0.8,
    xp: 12,
    meat: null,
    mats: [['f9_rune', 0.6]],
    beast: true,
    brain: 'f9_hoarder',
    art: { kind: 'paint', id: 'f9_hoarder' },
    mass: 1,
    flinch: 0.5,
    coins: 560,
    resume: 'flee',
    eye: '#ffe07a',
    gore: ['#6a4a8a', '#ffd24a', '#3a2a4a'],
  },
  // --- Гидра: тело, головы, скрытая голова, обрубок шеи.
  {
    id: 'f9boss',
    name: 'Многоглавая гидра',
    many: 'многоглавых гидр',
    hp: 820,
    dmg: 18,
    speed: 0,
    radius: 1.5,
    windup: 0.8,
    reach: 1,
    rest: 1,
    xp: 900,
    meat: null,
    mats: [],
    beast: true,
    brain: 'f9_body',
    art: { kind: 'paint', id: 'f9_body' },
    mass: 99,
    boss: true,
    noAlbino: true,
    fly: true,
    eye: '#ffe06a',
    gore: ['#1e3a2a', '#3e7a4a', '#a82a2a'],
  },
  {
    id: 'f9_head',
    name: 'Голова гидры',
    many: 'голов гидры',
    hp: 44,
    dmg: 21,
    speed: 2.6,
    radius: 0.42,
    windup: 0.6,
    reach: 0.55,
    rest: 0.9,
    xp: 40,
    meat: null,
    mats: [],
    beast: false,
    brain: 'f9_head',
    art: { kind: 'paint', id: 'f9_head' },
    mass: 3,
    boss: true,
    noAlbino: true,
    fly: true,
    eye: '#ffe06a',
    gore: ['#1e3a2a', '#a82a2a', '#3e7a4a'],
  },
  {
    id: 'f9_crown',
    name: 'Скрытая голова',
    many: 'скрытых голов',
    hp: 240,
    dmg: 20,
    speed: 3,
    radius: 0.55,
    windup: 0.7,
    reach: 0.6,
    rest: 1,
    xp: 200,
    meat: null,
    mats: [],
    beast: false,
    brain: 'f9_crown',
    art: { kind: 'paint', id: 'f9_crown' },
    mass: 6,
    boss: true,
    noAlbino: true,
    fly: true,
    eye: '#d0a0ff',
    gore: ['#1a1428', '#6a4aa8', '#e8e0ff'],
  },
  {
    id: 'f9_stump',
    name: 'Обрубок шеи',
    many: 'обрубков',
    hp: 5000,
    dmg: 0,
    speed: 0,
    radius: 0.34,
    windup: 1,
    reach: 0,
    rest: 1,
    xp: 0,
    meat: null,
    mats: [],
    beast: false,
    brain: 'f9_stump',
    art: { kind: 'paint', id: 'f9_stump' },
    mass: 99,
    noAlbino: true,
    flinch: 0,
    gore: ['#a82a2a', '#3e7a4a', '#5a1a14'],
  },
];

/** Затопленные руины: ящеры, жабы, змеи; пиявки — хвостом стаи. */
const spawnRuins: SpawnSpec = {
  mobs: [
    ['f9_lizard', 34],
    ['f9_toad', 26],
    ['f9_serpent', 14],
    ['f9_leech', 14],
    ['f9_priest', 7],
    ['f9_kobold', 5],
  ],
  density: 0.8,
  pack: [1, 2],
  filler: 'f9_leech',
  // Стая: ящеры с копьями, изредка с жрецом во главе, хвостом — жаба.
  group: (i, n, rnd) =>
    i === 0 && rnd() < 0.35 ? 'f9_priest' : i < n - 1 ? 'f9_lizard' : 'f9_toad',
  horde: null,
  treasure: 'f9_hoarder',
  nest: () => 'f9_toad',
};

const spawnMaze: SpawnSpec = {
  mobs: [
    ['f9_kobold', 36],
    ['f9_serpent', 22],
    ['f9_lizard', 20],
    ['f9_priest', 12],
    ['f9_wisp', 10],
  ],
  density: 0.85,
  pack: [1, 2],
  filler: 'f9_kobold',
  group: (i, _n, rnd) => (i === 0 ? (rnd() < 0.5 ? 'f9_priest' : 'f9_serpent') : 'f9_kobold'),
  horde: null,
  treasure: 'f9_hoarder',
  nest: () => 'f9_kobold',
};

const spawnLair: SpawnSpec = {
  mobs: [
    ['f9_lizard', 32],
    ['f9_toad', 24],
    ['f9_leech', 18],
    ['f9_serpent', 14],
    ['f9_wisp', 12],
  ],
  density: 0.9,
  pack: [2, 2],
  filler: 'f9_leech',
  group: (i, n, rnd) =>
    i === 0 && rnd() < 0.3 ? 'f9_priest' : i < n - 1 ? 'f9_lizard' : 'f9_serpent',
  horde: null,
  treasure: 'f9_hoarder',
  nest: () => 'f9_toad',
};

export const F9: FloorDef = {
  id: 9,
  name: 'Лабиринт гидры',
  lead: 'Затопленные руины и круги, что переносят в пару. В чёрной заводи — гидра, у которой отрастают головы.',
  mapVer: 1,
  areas: [
    {
      id: F9_RUINS,
      name: 'Затопленные руины',
      lead: 'Болото съело город. Круги на полу — переносят.',
      tier: 8,
      level: 9,
      ambient: 0.46,
      rows: MAP_F9_RUINS,
      skin: {
        floor: 'slab',
        wall: 'rock',
        tint: { mul: [0.84, 1.02, 0.86], mix: '#1e3a24', k: 0.16 },
        fog: '#040a06',
      },
      legend: LEGEND,
      mine: 'f9mine',
      spawn: spawnRuins,
    },
    {
      id: F9_MAZE,
      name: 'Лабиринт кругов',
      lead: 'Ходы, которых нет на полу. Смотри на цвет круга.',
      tier: 8,
      level: 9,
      ambient: 0.42,
      rows: MAP_F9_MAZE,
      skin: {
        floor: 'slab',
        wall: 'brick',
        tint: { mul: [0.86, 0.9, 1.08], mix: '#2a1e4a', k: 0.14 },
        fog: '#07050c',
      },
      legend: LEGEND,
      mine: 'f9mine2',
      spawn: spawnMaze,
    },
    {
      id: F9_LAIR,
      name: 'Логово гидры',
      lead: 'Чёрная заводь. Вода поднимается за спиной.',
      tier: 8,
      level: 9,
      ambient: 0.4,
      rows: MAP_F9_LAIR,
      skin: {
        floor: 'ground',
        wall: 'rock',
        tint: { mul: [0.78, 0.95, 0.95], mix: '#0e2a2c', k: 0.18 },
        fog: '#030708',
      },
      legend: LEGEND,
      spawn: spawnLair,
    },
  ],
  boss: {
    id: 'f9boss',
    name: 'Многоглавая гидра',
    lead: 'Озеро в сердце логова',
    area: F9_LAIR,
    restMs: 20 * 60_000,
    mob: 'f9boss',
    script: 'f9boss',
    parts: ['f9boss', 'f9_head', 'f9_crown'],
    loot: (rnd) => ({
      tokens: 70 + Math.floor(rnd() * 40),
      keys: rnd() < 0.8 ? 1 : 0,
      coins: 72_000,
      mats: {
        f9_heart: 1,
        f9mat: 4 + Math.floor(rnd() * 4),
        f9_mana: 2 + Math.floor(rnd() * 3),
      },
    }),
  },
  mines: [
    {
      id: 'f9mine',
      name: 'Шахта руин',
      area: F9_RUINS,
      windowMs: 60 * 60_000,
      ores: [16, 17],
      share: [0.22, 0.29, 0.36, 0.44, 0.52],
      pyrite: 0,
      blocks: 1.7,
    },
    {
      id: 'f9mine2',
      name: 'Шахта кругов',
      area: F9_MAZE,
      windowMs: 3 * 60 * 60_000,
      ores: [16, 17],
      share: [0.28, 0.36, 0.44, 0.52, 0.6],
      pyrite: 0,
      blocks: 2.3,
    },
  ],
  mobs: MOBS,
  meats: [
    { id: 'f9_tail', name: 'Хвост ящера', price: 60, heal: 0.3 },
    { id: 'f9_frogleg', name: 'Жабьи окорочка', price: 40, heal: 0.2 },
    { id: 'f9_snake', name: 'Змеиное филе', price: 55, heal: 0.26 },
  ],
  mats: [
    {
      id: 'f9mat',
      name: 'Болотная чешуя',
      price: 420,
      lead: 'Чешуя ящеров топи: не гниёт в воде.',
    },
    {
      id: 'f9_toxin',
      name: 'Жабий яд',
      price: 480,
      lead: 'Мутная капля в пузырьке. Не нюхать.',
    },
    {
      id: 'f9_rune',
      name: 'Осколок круга',
      price: 560,
      lead: 'Кусок руны с пола лабиринта. Ещё теплится.',
    },
    {
      id: 'f9_mana',
      name: 'Кристалл маны',
      price: 640,
      lead: 'Светится изнутри. Гудит, если поднести к кругу.',
    },
    {
      id: 'f9_root',
      name: 'Живой корень',
      price: 520,
      lead: 'Шевелится даже отрубленный.',
    },
    {
      id: 'f9_heart',
      name: 'Сердце гидры',
      price: 60_000,
      lead: 'Трофей. Бьётся: гидра отрастила бы и его.',
      stack: 1,
    },
  ],
  music: { explore: 'depths', boss: 'boss' },
  cover: '/ui/areas/f9.png',
};
